### ISSUE TITLE
Fix typo in the header

### ISSUE THREAD

**Issue by volodymyr-kushnir** [FilipVoloshin/BSA17GIT#4]
They had a typo in the article title — it should be Wan**n**a Decrypt0r 2.0, double-n — if I'm not mistaken.

**Comment by FilipVoloshin** [comment]
@volodymyr-kushnir yes, you are right, thanks for help. I'll correct this in a few minutes

**Comment by FilipVoloshin** [comment]
Issue is solved (b610da6) and it can be closed.
